### ISSUE TITLE
How to implement feature learning?

### ISSUE THREAD

**Issue by SWRDFK** [Simon4Yan/Learning-via-Translation#11]
Hi, author! Thank for your perfect work.I have met some problems with feature learning this part.
cd $IDE_ROOT
  # train IDE on Market-1501
  ./experiments/market/train_IDE_ResNet_50_baseline.sh  
I execute this command，and the error is : caffe /build/.../caffe : not a dictionary.
So how can I make this work? May I execute IDE with pytorch? Waiting for your reply. Thank you!

**Comment by Simon4Yan** [comment]
See here: https://github.com/Simon4Yan/Person_reID_baseline_pytorch
