### ISSUE TITLE
 ImageNet pretrained caffe model

### ISSUE THREAD

**Issue by nandini269** [Simon4Yan/Learning-via-Translation#13]
When we try to train the baseline using train_IDE_ResNET_50_baseline.sh we get an error saying that this directory 'data/imagenet_models//ResNet_50.caffemodel' was not found. We only found a readme file  in 'imagenet_models'. We were wondering if we are supposed to add an ImageNet pretrained ResNet caffe model in this directory? If so, could you provide a link or tell us where to find it?

Thanks!

**Comment by Simon4Yan** [comment]
please see https://github.com/zhunzhong07/IDE-baseline-Market-1501 for the training details of IDE. Good luck to you.
