### ISSUE TITLE
Difference between ResNet_50 and ResNet_50_domain model

### ISSUE THREAD

**Issue by GuangxingHan** [Simon4Yan/Learning-via-Translation#15]
Why do you create two difference models for ResNet_50 and ResNet_50_domain? What's the difference and why? Thanks for your help.

**Comment by Simon4Yan** [comment]
The difference is the **path** of the training dataset. ResNet_50 uses the original images for direct transfer, while ResNet_50_domain uses translated images for transfer experiment. Thanks for your question.

**Comment by GuangxingHan** [comment]
@Simon4Yan . Thanks for your kind response. However, I notice that the params of conv1, res2 and all bn layers are fixed in your training prototxt file of ResNet_50_domain. The rank1 and mAP accuracy both drop if these params are also learned in training. So do you encounter this problem?

**Comment by Simon4Yan** [comment]
YES！ We noticed this issue to readers when we released the code. See here, https://github.com/Simon4Yan/Learning-via-Translation/issues/1.
