### ISSUE TITLE
Where is the LMP in code?

### ISSUE THREAD

**Issue by SWRDFK** [Simon4Yan/Learning-via-Translation#18]
Hello, I would like to learn about Local Max Pooling (LMP), but I can't find it in all the files. Could you please tell me where it is? Thanks!

**Comment by Simon4Yan** [comment]
For Caffe framework:
layer {
	bottom: "res5c"
	top: "pool_part"
	name: "pool_part"
	type: "Pooling"
	pooling_param {
		kernel_w: 7
                kernel_h: 4
		stride_h: 3
                stride_w: 1
		pool: MAX
	}
}


Like this, and you should calculate the output dimension. Good luck to you.

For Pytorch:
just try: nn.AdaptiveMaxpooling((7,1))

Good luck to you!
