### ISSUE TITLE
how much size of target dataset is needed?

### ISSUE THREAD

**Issue by a462428** [Simon4Yan/Learning-via-Translation#2]
Hi,

I wanna try transfer market1501 to my own dataset

I wonder that have you ever tried how much size of target dataset is needed for

getting good transfer result for SPGAN??

**Comment by Simon4Yan** [comment]
Hi,

In the paper, we use the training data sets of duke and market to train SPGAN/ CycleGAN. We does not check how much size of target dataset is needed. And I think that it would be great that the number of Ur data is almost the same with Market.

Good luck!
