### ISSUE TITLE
test error when load net

### ISSUE THREAD

**Issue by yja1** [Simon4Yan/Learning-via-Translation#6]
when test use your model,  this line "net = caffe.Net(model, weights, 'test');" cause error:

run extract_feature.m
*** Error in `/MATLABR2014a/bin/glnxa64/MATLAB': double free or corruption (out): 0x00007fac72ae6560 ***

**Comment by Simon4john** [comment]
Hello, the evaluation code is modified from this [project](https://github.com/zhunzhong07/IDE-baseline-Market-1501). Maybe you can check this project. 

Besides, this problem seems matlab's problem, but I have no idea about this problem now.
