### ISSUE TITLE
The result is lower than this paper

### ISSUE THREAD

**Issue by ssFade** [Simon4Yan/Learning-via-Translation#9]
when I training on market and testing on duke, the rank-1 and mAP are around 35%,18%.when I training on duke and testing on market, the result is as same as this paper. If there are some different set when testing on duke? The direct transfer rank-1 is 30% when testing on duke, it's also lower than paper..

**Comment by Simon4Yan** [comment]
Did you use our code provided in this project?

**Comment by ssFade** [comment]
Thanks for your reply. 
Yes, I just used your code.  The result of IDE model is not so high as  the paper.  The supervise  result is low too.

**Comment by Simon4Yan** [comment]
My friend did a experiment: https://github.com/Simon4Yan/Learning-via-Translation/issues/1

**Comment by ssFade** [comment]
Thanks. I used caffe for IDE model. I'll try pytorch.
